version: 1
formatters:
  simple:
    format: "%(asctime)s [%(module)s:%(lineno)s] %(levelname)s -- %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [console]
loggers:
  sampleLogger:
    level: DEBUG
    handlers: [console]
    propagate: no
#  file:
#    class : logging.handlers.RotatingFileHandler
#    formatter: precise
#    filename: logconfig.log
#    maxBytes: 1024
#    backupCount: 3