config_name: Rover-AI Robotics
config_desc: This is a AI based Rover Application

rover_cam:
  device_id: 0

navigation_config:
  motor_L:
    gpio_pins:
      enable: 2
      in1: 3
      in2: 4
    pwm_default: 100
  motor_R:
    gpio_pins:
      enable: 5
      in1: 6
      in2: 7
    pwm_default: 100

key_events:
  W: move_forward
  S: move_backward
  A: rotate_left
  D: rotate_right
  SPACE: stop
  Q: rotate_360
  E: exit

rover_qr_configs:
  out_path: resources/generated/qr_codes
  embed_log: resources/images/logo.jpg

  qr_app_name: Rover-AI
  action_configs:
    move_forward:
      qr_action_id: 9001
      qr_action_details: Move rover forward
    move_backward:
      qr_action_id: 9002
      qr_action_details: Move rover backward
    rotate_left:
      qr_action_id: 9003
      qr_action_details: Rotate rover left
    rotate_right:
      qr_action_id: 9004
      qr_action_details: Rotate rover right
    stop:
      qr_action_id: 9005
      qr_action_details: Make rover stop
    move_360:
      qr_action_id: 9006
      qr_action_details: Rover rotate 360
